version: '3.1'

services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/example
      - ./php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
  nginx:
    image: nginx:1.19
    links:
      - php
    ports:
      - 8085:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/example
  mysql:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_task
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql:/etc/mysql/volume:ro